"""add change params to int

Revision ID: 1cc89190e0fd
Revises: 28bce0ad4e05
Create Date: 2023-09-15 12:49:41.938153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cc89190e0fd'
down_revision = '28bce0ad4e05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
