"""add change Comp params

Revision ID: 28bce0ad4e05
Revises: 94dc416a51d2
Create Date: 2023-09-15 11:31:41.488397

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '28bce0ad4e05'
down_revision = '94dc416a51d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('computation', sa.Column('parameter', sa.Float(), nullable=False))
    op.drop_column('computation', 'api_parameter_json')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('computation', sa.Column('api_parameter_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('computation', 'parameter')
    # ### end Alembic commands ###
