"""add comp output table

Revision ID: 94dc416a51d2
Revises: e63d487613bc
Create Date: 2023-09-15 11:17:15.611260

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '94dc416a51d2'
down_revision = 'e63d487613bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('computationOutput',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('computed_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.ForeignKeyConstraint(['computed_by'], ['computation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('computation', 'value')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('computation', sa.Column('value', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_table('computationOutput')
    # ### end Alembic commands ###
